// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-variants/AIForward.tsx": () => import("../components/mockups/landing-variants/AIForward.tsx"),
  "./components/mockups/landing-variants/DashboardLed.tsx": () => import("../components/mockups/landing-variants/DashboardLed.tsx"),
  "./components/mockups/landing-variants/ProblemSolution.tsx": () => import("../components/mockups/landing-variants/ProblemSolution.tsx")
};
